print ("----------------------------------------")
print ("Subject: Computer Programming 1")
print ("My First Program in Python")
print ("Created by: Nathan Allyn S. Acosta")
print ("Date Presented Aug 20,2024")
print("It takes 2-3 hours to create,test run, and analyse")
print ("----------------------------------------")
print()
print()
# label lang tag note para iwas tag sakit sa mata kung asa dapita na og asa ko nag kulang 
print("★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★")
print()
print("Python Arithmetic Operators")
print()
print("The '*' Operator is Name Multiplication")
print('The "/" Operator is Division')
print('The "+" Operator is kabalo naka syaro nagyud')
print('The "-" Operator is grabe nagyud og wala gihapon')
print()
print("★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★")
print()
print()
print()
print()
print()
print("───★──────★──────★──────★──────★──────★──────★──────★──────★──────★──────★───")
print()
print("Basic Calculator Part")
print()
print ("Addition")
print("224 + 244 =_____")
print("So, The total value of the plus is",224+244)
print()
print("Subtraction")
print(" 6969 - 1919 is =______")
print(" The Answer is",6969 - 1919)
print()
print("Division")
print("The Problem is 1245 divided by 99")
print(1245/99, "is the answer")
print()
print("Multiplication")
print("987 * 567 is equals to")
print(987*567)
print()
print("───★──────★──────★──────★──────★──────★──────★──────★──────★──────★──────★───")
print()
print()
print()
print()
print()
Xerostomia = 6969
Hematemesis = 7979
Fibromyalgia = 4444
print("─── ⋆⋅☆⋅⋆ ──Information─── ⋆⋅☆⋅⋆ ──")
print()
print("Xerostomia = 6979")
print("Hematemesis = 7969")
print("fibromyalgia = 4444")
print()
print("───────────────────────────────────")
print()
print()
print()
print()
print("── ─── ⋆⋅☆⋅⋆ ── ─── ─── ⋆⋅☆⋅⋆ ── ─── ⋆⋅☆⋅⋆ ── ─── Multiple Calculations ── ─── ⋆⋅☆⋅⋆ ── ─── ⋆⋅☆⋅⋆ ── ───")
print("Triple Calculations")
print(f"{Xerostomia} X {Fibromyalgia} is equals to")
print("=", Xerostomia*Fibromyalgia)
print(f"{Fibromyalgia} X {Hematemesis} ÷ {Xerostomia} is equals to")
print("=", Fibromyalgia*Hematemesis/Xerostomia)
print(f"{Hematemesis} ÷ {Xerostomia} + {Hematemesis} is equals to")
print("=",Hematemesis/Xerostomia+Hematemesis)
print()
print()
print("Quadruple Calculations")
print()
print("244 X 44  ÷ 24 + 44 -44 =________")
Myocardial_Infarction = (
    "The Total value of the problem given is equals to",
    244 * 44 / 24 + 44 - 44)
print(Myocardial_Infarction)
print()
print("── ─── ⋆⋅☆⋅⋆ ── ─── ─── ⋆⋅☆⋅⋆ ── ─── ⋆⋅☆⋅⋆ ── ─── End of Code ── ─── ⋆⋅☆⋅⋆ ── ─── ⋆⋅☆⋅⋆ ── ─── ⋆⋅☆⋅⋆ ──")
